/// Stores the three identities used by the synchronization architecture.
///
/// `local_id` belongs only to the local Drift database.
/// `app_id` is generated by the client and never changes.
/// `global_id` is assigned by Supabase and never changes once known.
///
/// `sync_id` deliberately does not appear in this API: it is reserved for
/// synchronization bookkeeping rather than domain-entity identity.
abstract interface class EntityIdentityRepository {
  Future<EntityIdentity> ensure(String entityType, int localId);
  Future<EntityIdentity?> get(String entityType, int localId);
  Future<void> setGlobalId({
    required String entityType,
    required int localId,
    required String globalId,
  });
}

class EntityIdentity {
  const EntityIdentity({
    required this.entityType,
    required this.localId,
    required this.appId,
    required this.globalId,
  });

  final String entityType;
  final int localId;
  final String appId;
  final String? globalId;
}
