-- Three-ID identity model.
-- app_id is created by the client and is the durable client-side identity.
-- global_id is generated by Supabase and is the server-side canonical identity.
-- sync_id remains the legacy synchronization/compatibility identifier until
-- the transport migration is complete; it is no longer the domain identity.

create extension if not exists pgcrypto;

alter table public.players
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.teams
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.tournaments
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.matches
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.innings
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.ball_events
  add column if not exists app_id text,
  add column if not exists global_id uuid default gen_random_uuid();

-- Existing rows need a deterministic client identity during the transition.
-- The legacy sync_id was already unique and device-independent in the
-- deployed contract, so it is safe as a one-time compatibility seed.
update public.players set app_id = sync_id where app_id is null;
update public.teams set app_id = sync_id where app_id is null;
update public.tournaments set app_id = sync_id where app_id is null;
update public.matches set app_id = sync_id where app_id is null;
update public.innings set app_id = sync_id where app_id is null;
update public.ball_events set app_id = sync_id where app_id is null;

-- Repair any legacy NULL global IDs before enforcing the contract.
update public.players set global_id = gen_random_uuid() where global_id is null;
update public.teams set global_id = gen_random_uuid() where global_id is null;
update public.tournaments set global_id = gen_random_uuid() where global_id is null;
update public.matches set global_id = gen_random_uuid() where global_id is null;
update public.innings set global_id = gen_random_uuid() where global_id is null;
update public.ball_events set global_id = gen_random_uuid() where global_id is null;

alter table public.players alter column app_id set not null;
alter table public.players alter column global_id set not null;
alter table public.teams alter column app_id set not null;
alter table public.teams alter column global_id set not null;
alter table public.tournaments alter column app_id set not null;
alter table public.tournaments alter column global_id set not null;
alter table public.matches alter column app_id set not null;
alter table public.matches alter column global_id set not null;
alter table public.innings alter column app_id set not null;
alter table public.innings alter column global_id set not null;
alter table public.ball_events alter column app_id set not null;
alter table public.ball_events alter column global_id set not null;

create unique index if not exists players_app_id_uidx on public.players(app_id);
create unique index if not exists players_global_id_uidx on public.players(global_id);
create unique index if not exists teams_app_id_uidx on public.teams(app_id);
create unique index if not exists teams_global_id_uidx on public.teams(global_id);
create unique index if not exists tournaments_app_id_uidx on public.tournaments(app_id);
create unique index if not exists tournaments_global_id_uidx on public.tournaments(global_id);
create unique index if not exists matches_app_id_uidx on public.matches(app_id);
create unique index if not exists matches_global_id_uidx on public.matches(global_id);
create unique index if not exists innings_app_id_uidx on public.innings(app_id);
create unique index if not exists innings_global_id_uidx on public.innings(global_id);
create unique index if not exists ball_events_app_id_uidx on public.ball_events(app_id);
create unique index if not exists ball_events_global_id_uidx on public.ball_events(global_id);

comment on column public.players.app_id is 'Client-created durable entity identity.';
comment on column public.players.global_id is 'Server-created canonical entity identity.';
comment on column public.teams.app_id is 'Client-created durable entity identity.';
comment on column public.teams.global_id is 'Server-created canonical entity identity.';
comment on column public.tournaments.app_id is 'Client-created durable entity identity.';
comment on column public.tournaments.global_id is 'Server-created canonical entity identity.';
comment on column public.matches.app_id is 'Client-created durable entity identity.';
comment on column public.matches.global_id is 'Server-created canonical entity identity.';
comment on column public.innings.app_id is 'Client-created durable entity identity.';
comment on column public.innings.global_id is 'Server-created canonical entity identity.';
comment on column public.ball_events.app_id is 'Client-created durable entity identity.';
comment on column public.ball_events.global_id is 'Server-created canonical entity identity.';
