-- Extend the three-ID model to relationship entities.
-- Existing relationship rows receive compatibility UUIDs generated by the
-- server. New rows must provide their client-created app_id.

create extension if not exists pgcrypto;

alter table public.team_players
  add column if not exists app_id uuid default gen_random_uuid(),
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.tournament_teams
  add column if not exists app_id uuid default gen_random_uuid(),
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.match_teams
  add column if not exists app_id uuid default gen_random_uuid(),
  add column if not exists global_id uuid default gen_random_uuid();

alter table public.match_players
  add column if not exists app_id uuid default gen_random_uuid(),
  add column if not exists global_id uuid default gen_random_uuid();

update public.team_players set app_id = gen_random_uuid() where app_id is null;
update public.team_players set global_id = gen_random_uuid() where global_id is null;
update public.tournament_teams set app_id = gen_random_uuid() where app_id is null;
update public.tournament_teams set global_id = gen_random_uuid() where global_id is null;
update public.match_teams set app_id = gen_random_uuid() where app_id is null;
update public.match_teams set global_id = gen_random_uuid() where global_id is null;
update public.match_players set app_id = gen_random_uuid() where app_id is null;
update public.match_players set global_id = gen_random_uuid() where global_id is null;

alter table public.team_players alter column app_id set not null;
alter table public.team_players alter column global_id set not null;
alter table public.tournament_teams alter column app_id set not null;
alter table public.tournament_teams alter column global_id set not null;
alter table public.match_teams alter column app_id set not null;
alter table public.match_teams alter column global_id set not null;
alter table public.match_players alter column app_id set not null;
alter table public.match_players alter column global_id set not null;

create unique index if not exists team_players_app_id_uidx on public.team_players(app_id);
create unique index if not exists team_players_global_id_uidx on public.team_players(global_id);
create unique index if not exists tournament_teams_app_id_uidx on public.tournament_teams(app_id);
create unique index if not exists tournament_teams_global_id_uidx on public.tournament_teams(global_id);
create unique index if not exists match_teams_app_id_uidx on public.match_teams(app_id);
create unique index if not exists match_teams_global_id_uidx on public.match_teams(global_id);
create unique index if not exists match_players_app_id_uidx on public.match_players(app_id);
create unique index if not exists match_players_global_id_uidx on public.match_players(global_id);

comment on column public.team_players.app_id is 'Client-created durable relationship identity.';
comment on column public.team_players.global_id is 'Server-created canonical relationship identity.';
comment on column public.tournament_teams.app_id is 'Client-created durable relationship identity.';
comment on column public.tournament_teams.global_id is 'Server-created canonical relationship identity.';
comment on column public.match_teams.app_id is 'Client-created durable relationship identity.';
comment on column public.match_teams.global_id is 'Server-created canonical relationship identity.';
comment on column public.match_players.app_id is 'Client-created durable relationship identity.';
comment on column public.match_players.global_id is 'Server-created canonical relationship identity.';
